#coding: utf8

RESULT_SUCCEED                      = 0
RESULT_FAILED                       = 1

RESULT_FAILED_ACCOUNT_INVALID       = 2

RESULT_FAILED_NO_LOGIN              = 4
RESULT_FAILED_NAME_EXISTED          = 5
RESULT_FAILED_ACCOUNT_EMPTY         = 7
RESULT_FAILED_ACCOUNT_DISABLED      = 8
RESULT_FAILED_ACCOUNT_LENGTH_EQUALS_ZERO       = 9
RESULT_FAILED_ACCOUNT_LENGTH       = 10
RESULT_FAILED_ACCOUNT_EXCEPTION     = 12 # 账号异常
RESULT_FAILED_CODE_FILL = 11
RESULT_FAILED_TOEKN = 13


RESULT_FAILED_SMS_EMPTY = -1100
RESULT_FAILED_SMS_SEND_FAILED = -1104
RESULT_FAILED_SMS_NOT_EQUALS = -1102
RESULT_FAILED_SMS_EXITS = -1103





RESULT_FAILED_INVALID_USER          = -10000
RESULT_FAILED_INVALID_TABLE         = -10002
RESULT_FAILED_ALREADY_READY         = -10003
RESULT_FAILED_ALREADY_START         = -10004
RESULT_FAILED_NOT_START             = -10005
RESULT_FAILED_INVALID_TURN          = -10006
RESULT_FAILED_SHOW_HAND             = -10007
RESULT_FAILED_NO_ENOUGH_GOLD        = -10008
RESULT_FAILED_INVALID_GAMBLER       = -10009
RESULT_FAILED_INVALID_GOLD          = -10010
RESULT_FAILED_INVALID_ROUND         = -10011
RESULT_FAILED_MORE_GAMBLERS         = -10012
RESULT_FAILED_ALREADY_SIT           = -10013
RESULT_FAILED_TABLE_IS_FULL			= -10014
RESULT_FAILED_LESS_GOLD          	= -10020
RESULT_FAILED_MORE_GOLD          	= -10021
RESULT_FAILED_GAME_NOT_STARTED      = -10022
RESULT_FAILED_INVALID_SHOW_HAND     = -10023

# 登录
RESULT_FAILED_ACCOUNT_OR_PASSWORD_INVALID      = -100 # 账号或密码不对
# 维护状态
RESULT_FAILED_HALL_FIX      = -99 # 大厅维护状态
# 修改、注册手机
RESULT_FAILED_VERIFY_ERROR          = -20         # 验证失败
RESULT_FAILED_PASSWORD_EMPTY        = -21
RESULT_FAILED_MOBILE_EXISTS         = -22         # 手机账户已经存在
RESULT_FAILED_ACCOUNT_EMPTY         = -23         # 账户不存在
RESULT_FAILED_ACCOUNT_PASSWORD      = -24         # 密码错误
RESULT_FAILED_NO_TALK = -25                       # 禁止说话

# 商店
RESULT_FAILED_INVALID_AUTH          = -20001      # VIP权限不足
RESULT_FAILED_SHOP_DIAMOND          = -20002      # 钻石不足
RESULT_FAILED_SHOP                  = -20003      # 交易失败
RESULT_FAILED_INVALID_SHOP          = -20004      # 交易下架

# 背包
RESULT_FAILED_INVALID_BAG           = -20010      # 背包中不存在相关道具
RESULT_FAILED_INVALID_RECORD        = -20011
RESULT_FAILED_RECEIVE_REWARD        = -20012
RESULT_FAILED_ANNOUCEMENT_EMPTY     = -20013     # 公告，不存在最新 的公告数据

# 踢人
RESULT_FAILED_NO_KICK               = -20090       # 不可踢人（游戏中或VIP等级6及以上）
# 兑换码
RESULT_FAILED_CODE                  = -20091       # 兑换失败
RESULT_FAILED_CODE_EXPIRED          = -20092       # 兑换码过期
RESULT_FAILED_CODE_FILL             = -20093       # 兑换码充值人数已满
RESULT_FAILED_CODE_USED             = -20094       # 当前用户已经使用过兑换码

# 邮件
RESULT_FAILED_MAIL                  = -20100       # 邮件已领取或不存在

# 签到
RESULT_FAILED_TODAY_SIGNED          = -20110       # 今日已签到
# 签到异常
RESULT_FAILED_SIGN_ERROR          = -20111

# 好友
RESULT_FAILED_INVALID_FRIEND        = -20200       # 添加好友失败
RESULT_FAILED_FRIEND_MAX            = -20201       # 超过好友上线
RESULT_FAILED_FRIEND_TARGET_MAX     = -20204       # 对方好友超过上限
RESULT_FAILED_HAS_FRIEND        = -20202       # 重复添加好友
RESULT_FAILED_MAKE_APPLY        = -20203       # 好友申请中
RESULT_FAILED_INVALID_FEEDBACK   = -20205      # feedback不能为空

# 奖励（任务）
RESULT_FAILED_INVALID_REWARD        = -20206       # 任务失败

# 银行
RESULT_FAILED_BANK_MAX             = -20300       # 超过银行上线

# 破产补助
RESULT_FAILED_BROKE_FULL          = -20400        # 领取超过破产补助

# 首冲
RESULT_FAILED_FIRST_CHARGE       = -20500         # 已经首冲过了

RESULT_FAILED_NO_ACTIVITY        = -20501         # 无活动数据
RESULT_FAILED_ACTIVITY           = -20502         # 已经充值过了
RESULT_FAILED_INVALID_TRANSFER   = -20503    # 不能转账给自己
RESULT_FAILED_INVALID_TRANSFER_LOW   = -20504 # 金币不够转账最低额度
RESULT_FAILED_INVALID_TRANSFER_TARGET   = -20505 # 目标不存在

########## 红黑大战
RESULT_FAILED_INVALID_RUNNING = -30001   # 游戏没有开始
RESULT_FAILED_INVALID_DECR = -30002   # 扣取用户金币异常
RESULT_FAILED_INVALID_IN_WAR = -30003 # 没有坐在牌桌内
RESULT_FAILED_INVALID_EXISTS = -30004 # 用户已经在牌桌内
RESULT_FAILED_INVALID_NOT_EXISTS = -30005 # 当前用户没有sit table
RESULT_FAILED_BET_OTHER = -30006   # 不能投注对方牌桌
RESULT_FAILED_BET_OVER = -30007   # 不能投注对方牌桌
RESULT_FAILED_WAR_FIX = -30008   # 红黑牌桌维护中

# 流量兑换
RESULT_FAILED_FLOW_STACK      = -30020   # 库存不足
RESULT_FAILED_FLOW_NOT_ENOUGH = -30021    # 用户流量卡不足
RESULT_FAILED_FLOW_REQUIRED   = -30022   # 信息填写不完整
RESULT_FAILED_FLOW_GSM        = -30023   # 手机制式不对
RESULT_FAILED_FLOW_INVALID    = -30024   # 订货失败

# 时时彩
RESULT_FAILED_AUTO_BET_ERROR  = -30030  # 自动投数量为0或没有自动投数据
RESULT_FAILED_NOT_BET_ERROR = -30031 # 结算阶段不能投注
RESULT_FAILED_LOTTERY_FIX = -30032 # 时时彩维护中
RESULT_FAILED_BET_MAX = -30033 # 时时彩投注超额

# 德州
RESULT_FAILED_ALL_WATCH = -30100  # 所有用户全部watch
RESULT_FAILED_INVALID_PLAYER = -30101 # 玩家不存在
RESULT_FAILED_TEXAS_FIX = -30102 # 德州维护中
