# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()



# import struct_pb2
from proto import struct_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bank.proto',
  package='cardgame',
  serialized_pb=_b('\n\nbank.proto\x12\x08\x63\x61rdgame\x1a\x0cstruct.proto\"\x1e\n\x0cQueryBankReq\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\x94#\"T\n\rQueryBankResp\x12\x0c\n\x04gold\x18\x01 \x01(\x03\x12\r\n\x05limit\x18\x02 \x01(\x03\x12\x16\n\x0enext_vip_limit\x18\x03 \x01(\x03\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\x95#\",\n\x0cSaveMoneyReq\x12\x0c\n\x04gold\x18\x01 \x02(\x03\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\x96#\"A\n\rSaveMoneyResp\x12 \n\x06result\x18\x01 \x01(\x0b\x32\x10.cardgame.Result\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\x97#\"N\n\x0fTransferGoldReq\x12\x0e\n\x06target\x18\x01 \x02(\x05\x12\x0c\n\x04gold\x18\x02 \x02(\x03\x12\r\n\x05\x63heck\x18\x03 \x01(\x05\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\x98#\"q\n\x10TransferGoldResp\x12\x0c\n\x04nick\x18\x01 \x01(\t\x12\x0b\n\x03\x66\x65\x65\x18\x02 \x01(\x03\x12\x10\n\x08\x66\x65\x65_rate\x18\x03 \x01(\x05\x12 \n\x06result\x18\x04 \x01(\x0b\x32\x10.cardgame.Result\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\x99#B\"\n\x18\x63om.zhili.cardgame.protoB\x04\x42\x61nkH\x03')
  ,
  dependencies=[struct_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_QUERYBANKREQ_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.QueryBankReq.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=4500,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=54,
  serialized_end=68,
)
_sym_db.RegisterEnumDescriptor(_QUERYBANKREQ_DEF)

_QUERYBANKRESP_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.QueryBankResp.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=4501,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=140,
  serialized_end=154,
)
_sym_db.RegisterEnumDescriptor(_QUERYBANKRESP_DEF)

_SAVEMONEYREQ_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.SaveMoneyReq.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=4502,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=186,
  serialized_end=200,
)
_sym_db.RegisterEnumDescriptor(_SAVEMONEYREQ_DEF)

_SAVEMONEYRESP_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.SaveMoneyResp.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=4503,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=253,
  serialized_end=267,
)
_sym_db.RegisterEnumDescriptor(_SAVEMONEYRESP_DEF)

_TRANSFERGOLDREQ_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.TransferGoldReq.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=4504,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=333,
  serialized_end=347,
)
_sym_db.RegisterEnumDescriptor(_TRANSFERGOLDREQ_DEF)

_TRANSFERGOLDRESP_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.TransferGoldResp.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=4505,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=448,
  serialized_end=462,
)
_sym_db.RegisterEnumDescriptor(_TRANSFERGOLDRESP_DEF)


_QUERYBANKREQ = _descriptor.Descriptor(
  name='QueryBankReq',
  full_name='cardgame.QueryBankReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _QUERYBANKREQ_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=68,
)


_QUERYBANKRESP = _descriptor.Descriptor(
  name='QueryBankResp',
  full_name='cardgame.QueryBankResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gold', full_name='cardgame.QueryBankResp.gold', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit', full_name='cardgame.QueryBankResp.limit', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='next_vip_limit', full_name='cardgame.QueryBankResp.next_vip_limit', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _QUERYBANKRESP_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=154,
)


_SAVEMONEYREQ = _descriptor.Descriptor(
  name='SaveMoneyReq',
  full_name='cardgame.SaveMoneyReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gold', full_name='cardgame.SaveMoneyReq.gold', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SAVEMONEYREQ_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=200,
)


_SAVEMONEYRESP = _descriptor.Descriptor(
  name='SaveMoneyResp',
  full_name='cardgame.SaveMoneyResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='cardgame.SaveMoneyResp.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SAVEMONEYRESP_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=267,
)


_TRANSFERGOLDREQ = _descriptor.Descriptor(
  name='TransferGoldReq',
  full_name='cardgame.TransferGoldReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='cardgame.TransferGoldReq.target', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gold', full_name='cardgame.TransferGoldReq.gold', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='check', full_name='cardgame.TransferGoldReq.check', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRANSFERGOLDREQ_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=347,
)


_TRANSFERGOLDRESP = _descriptor.Descriptor(
  name='TransferGoldResp',
  full_name='cardgame.TransferGoldResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nick', full_name='cardgame.TransferGoldResp.nick', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fee', full_name='cardgame.TransferGoldResp.fee', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fee_rate', full_name='cardgame.TransferGoldResp.fee_rate', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='cardgame.TransferGoldResp.result', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRANSFERGOLDRESP_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=462,
)

_QUERYBANKREQ_DEF.containing_type = _QUERYBANKREQ
_QUERYBANKRESP_DEF.containing_type = _QUERYBANKRESP
_SAVEMONEYREQ_DEF.containing_type = _SAVEMONEYREQ
_SAVEMONEYRESP.fields_by_name['result'].message_type = struct_pb2._RESULT
_SAVEMONEYRESP_DEF.containing_type = _SAVEMONEYRESP
_TRANSFERGOLDREQ_DEF.containing_type = _TRANSFERGOLDREQ
_TRANSFERGOLDRESP.fields_by_name['result'].message_type = struct_pb2._RESULT
_TRANSFERGOLDRESP_DEF.containing_type = _TRANSFERGOLDRESP
DESCRIPTOR.message_types_by_name['QueryBankReq'] = _QUERYBANKREQ
DESCRIPTOR.message_types_by_name['QueryBankResp'] = _QUERYBANKRESP
DESCRIPTOR.message_types_by_name['SaveMoneyReq'] = _SAVEMONEYREQ
DESCRIPTOR.message_types_by_name['SaveMoneyResp'] = _SAVEMONEYRESP
DESCRIPTOR.message_types_by_name['TransferGoldReq'] = _TRANSFERGOLDREQ
DESCRIPTOR.message_types_by_name['TransferGoldResp'] = _TRANSFERGOLDRESP

QueryBankReq = _reflection.GeneratedProtocolMessageType('QueryBankReq', (_message.Message,), dict(
  DESCRIPTOR = _QUERYBANKREQ,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.QueryBankReq)
  ))
_sym_db.RegisterMessage(QueryBankReq)

QueryBankResp = _reflection.GeneratedProtocolMessageType('QueryBankResp', (_message.Message,), dict(
  DESCRIPTOR = _QUERYBANKRESP,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.QueryBankResp)
  ))
_sym_db.RegisterMessage(QueryBankResp)

SaveMoneyReq = _reflection.GeneratedProtocolMessageType('SaveMoneyReq', (_message.Message,), dict(
  DESCRIPTOR = _SAVEMONEYREQ,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.SaveMoneyReq)
  ))
_sym_db.RegisterMessage(SaveMoneyReq)

SaveMoneyResp = _reflection.GeneratedProtocolMessageType('SaveMoneyResp', (_message.Message,), dict(
  DESCRIPTOR = _SAVEMONEYRESP,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.SaveMoneyResp)
  ))
_sym_db.RegisterMessage(SaveMoneyResp)

TransferGoldReq = _reflection.GeneratedProtocolMessageType('TransferGoldReq', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFERGOLDREQ,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.TransferGoldReq)
  ))
_sym_db.RegisterMessage(TransferGoldReq)

TransferGoldResp = _reflection.GeneratedProtocolMessageType('TransferGoldResp', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFERGOLDRESP,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.TransferGoldResp)
  ))
_sym_db.RegisterMessage(TransferGoldResp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.zhili.cardgame.protoB\004BankH\003'))
# @@protoc_insertion_point(module_scope)
