# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# import struct_pb2
# import constant_pb2

# import struct_pb2
from proto import struct_pb2
from proto import constant_pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='cardgame',
  serialized_pb=_b('\n\nchat.proto\x12\x08\x63\x61rdgame\x1a\x0cstruct.proto\x1a\x0e\x63onstant.proto\"g\n\x0bSendChatReq\x12\x10\n\x08table_id\x18\x01 \x02(\x05\x12\x0f\n\x07message\x18\x02 \x02(\t\x12%\n\tchat_type\x18\x03 \x01(\x0e\x32\x12.cardgame.ChatType\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xb0\t\"@\n\x0cSendChatResp\x12 \n\x06result\x18\x01 \x01(\x0b\x32\x10.cardgame.Result\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xb1\t\"l\n\x0eSendEmotionReq\x12\x10\n\x08table_id\x18\x01 \x02(\x05\x12\x15\n\rtarget_player\x18\x02 \x02(\x05\x12\x12\n\nemotion_id\x18\x03 \x02(\x05\x12\r\n\x05\x63ount\x18\x04 \x02(\x05\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xba\t\"C\n\x0fSendEmotionResp\x12 \n\x06result\x18\x01 \x01(\x0b\x32\x10.cardgame.Result\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xbb\t\"u\n\tChatEvent\x12\x0e\n\x06sender\x18\x01 \x02(\x05\x12\x10\n\x08table_id\x18\x02 \x02(\x05\x12\x0f\n\x07message\x18\x03 \x02(\t\x12%\n\tchat_type\x18\x04 \x01(\x0e\x32\x12.cardgame.ChatType\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xe2\t\"z\n\x0c\x45motionEvent\x12\x0e\n\x06sender\x18\x01 \x02(\x05\x12\x10\n\x08table_id\x18\x02 \x02(\x05\x12\x15\n\rtarget_player\x18\x03 \x02(\x05\x12\x12\n\nemotion_id\x18\x04 \x02(\x05\x12\r\n\x05\x63ount\x18\x05 \x02(\x05\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xec\tB\"\n\x18\x63om.zhili.cardgame.protoB\x04\x43hatH\x03')
  ,
  dependencies=[struct_pb2.DESCRIPTOR,constant_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SENDCHATREQ_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.SendChatReq.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=1200,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=143,
  serialized_end=157,
)
_sym_db.RegisterEnumDescriptor(_SENDCHATREQ_DEF)

_SENDCHATRESP_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.SendChatResp.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=1201,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=209,
  serialized_end=223,
)
_sym_db.RegisterEnumDescriptor(_SENDCHATRESP_DEF)

_SENDEMOTIONREQ_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.SendEmotionReq.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=1210,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=319,
  serialized_end=333,
)
_sym_db.RegisterEnumDescriptor(_SENDEMOTIONREQ_DEF)

_SENDEMOTIONRESP_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.SendEmotionResp.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=1211,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=388,
  serialized_end=402,
)
_sym_db.RegisterEnumDescriptor(_SENDEMOTIONRESP_DEF)

_CHATEVENT_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.ChatEvent.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=1250,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=507,
  serialized_end=521,
)
_sym_db.RegisterEnumDescriptor(_CHATEVENT_DEF)

_EMOTIONEVENT_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.EmotionEvent.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=1260,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=631,
  serialized_end=645,
)
_sym_db.RegisterEnumDescriptor(_EMOTIONEVENT_DEF)


_SENDCHATREQ = _descriptor.Descriptor(
  name='SendChatReq',
  full_name='cardgame.SendChatReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table_id', full_name='cardgame.SendChatReq.table_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='cardgame.SendChatReq.message', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chat_type', full_name='cardgame.SendChatReq.chat_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SENDCHATREQ_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=157,
)


_SENDCHATRESP = _descriptor.Descriptor(
  name='SendChatResp',
  full_name='cardgame.SendChatResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='cardgame.SendChatResp.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SENDCHATRESP_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=223,
)


_SENDEMOTIONREQ = _descriptor.Descriptor(
  name='SendEmotionReq',
  full_name='cardgame.SendEmotionReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table_id', full_name='cardgame.SendEmotionReq.table_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_player', full_name='cardgame.SendEmotionReq.target_player', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='emotion_id', full_name='cardgame.SendEmotionReq.emotion_id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='cardgame.SendEmotionReq.count', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SENDEMOTIONREQ_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=333,
)


_SENDEMOTIONRESP = _descriptor.Descriptor(
  name='SendEmotionResp',
  full_name='cardgame.SendEmotionResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='cardgame.SendEmotionResp.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SENDEMOTIONRESP_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=402,
)


_CHATEVENT = _descriptor.Descriptor(
  name='ChatEvent',
  full_name='cardgame.ChatEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='cardgame.ChatEvent.sender', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='table_id', full_name='cardgame.ChatEvent.table_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='cardgame.ChatEvent.message', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chat_type', full_name='cardgame.ChatEvent.chat_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CHATEVENT_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=521,
)


_EMOTIONEVENT = _descriptor.Descriptor(
  name='EmotionEvent',
  full_name='cardgame.EmotionEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='cardgame.EmotionEvent.sender', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='table_id', full_name='cardgame.EmotionEvent.table_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_player', full_name='cardgame.EmotionEvent.target_player', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='emotion_id', full_name='cardgame.EmotionEvent.emotion_id', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='cardgame.EmotionEvent.count', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EMOTIONEVENT_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=523,
  serialized_end=645,
)

_SENDCHATREQ.fields_by_name['chat_type'].enum_type = constant_pb2._CHATTYPE
_SENDCHATREQ_DEF.containing_type = _SENDCHATREQ
_SENDCHATRESP.fields_by_name['result'].message_type = struct_pb2._RESULT
_SENDCHATRESP_DEF.containing_type = _SENDCHATRESP
_SENDEMOTIONREQ_DEF.containing_type = _SENDEMOTIONREQ
_SENDEMOTIONRESP.fields_by_name['result'].message_type = struct_pb2._RESULT
_SENDEMOTIONRESP_DEF.containing_type = _SENDEMOTIONRESP
_CHATEVENT.fields_by_name['chat_type'].enum_type = constant_pb2._CHATTYPE
_CHATEVENT_DEF.containing_type = _CHATEVENT
_EMOTIONEVENT_DEF.containing_type = _EMOTIONEVENT
DESCRIPTOR.message_types_by_name['SendChatReq'] = _SENDCHATREQ
DESCRIPTOR.message_types_by_name['SendChatResp'] = _SENDCHATRESP
DESCRIPTOR.message_types_by_name['SendEmotionReq'] = _SENDEMOTIONREQ
DESCRIPTOR.message_types_by_name['SendEmotionResp'] = _SENDEMOTIONRESP
DESCRIPTOR.message_types_by_name['ChatEvent'] = _CHATEVENT
DESCRIPTOR.message_types_by_name['EmotionEvent'] = _EMOTIONEVENT

SendChatReq = _reflection.GeneratedProtocolMessageType('SendChatReq', (_message.Message,), dict(
  DESCRIPTOR = _SENDCHATREQ,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.SendChatReq)
  ))
_sym_db.RegisterMessage(SendChatReq)

SendChatResp = _reflection.GeneratedProtocolMessageType('SendChatResp', (_message.Message,), dict(
  DESCRIPTOR = _SENDCHATRESP,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.SendChatResp)
  ))
_sym_db.RegisterMessage(SendChatResp)

SendEmotionReq = _reflection.GeneratedProtocolMessageType('SendEmotionReq', (_message.Message,), dict(
  DESCRIPTOR = _SENDEMOTIONREQ,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.SendEmotionReq)
  ))
_sym_db.RegisterMessage(SendEmotionReq)

SendEmotionResp = _reflection.GeneratedProtocolMessageType('SendEmotionResp', (_message.Message,), dict(
  DESCRIPTOR = _SENDEMOTIONRESP,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.SendEmotionResp)
  ))
_sym_db.RegisterMessage(SendEmotionResp)

ChatEvent = _reflection.GeneratedProtocolMessageType('ChatEvent', (_message.Message,), dict(
  DESCRIPTOR = _CHATEVENT,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.ChatEvent)
  ))
_sym_db.RegisterMessage(ChatEvent)

EmotionEvent = _reflection.GeneratedProtocolMessageType('EmotionEvent', (_message.Message,), dict(
  DESCRIPTOR = _EMOTIONEVENT,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.EmotionEvent)
  ))
_sym_db.RegisterMessage(EmotionEvent)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.zhili.cardgame.protoB\004ChatH\003'))
# @@protoc_insertion_point(module_scope)
