# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mail.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

#
# import struct_pb2
# import constant_pb2

from proto import struct_pb2
from proto import constant_pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='mail.proto',
  package='cardgame',
  serialized_pb=_b('\n\nmail.proto\x12\x08\x63\x61rdgame\x1a\x0cstruct.proto\x1a\x0e\x63onstant.proto\"3\n\x0c\x46\x65tchMailReq\x12\x13\n\x0bmax_mail_id\x18\x01 \x01(\x05\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xf8\n\">\n\rFetchMailResp\x12\x1d\n\x05mails\x18\x01 \x03(\x0b\x32\x0e.cardgame.Mail\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xf9\n\"7\n\x14ReceiveAttachmentReq\x12\x0f\n\x07mail_id\x18\x01 \x02(\x05\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xfa\n\"I\n\x15ReceiveAttachmentResp\x12 \n\x06result\x18\x01 \x01(\x0b\x32\x10.cardgame.Result\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xfb\n\"I\n\x0bSendMailReq\x12\n\n\x02to\x18\x01 \x02(\x05\x12\r\n\x05title\x18\x02 \x02(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x02(\t\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xfd\n\"\x1e\n\x0cSendMailResp\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xfe\nB\"\n\x18\x63om.zhili.cardgame.protoB\x04MailH\x03')
  ,
  dependencies=[struct_pb2.DESCRIPTOR,constant_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_FETCHMAILREQ_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.FetchMailReq.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=1400,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=91,
  serialized_end=105,
)
_sym_db.RegisterEnumDescriptor(_FETCHMAILREQ_DEF)

_FETCHMAILRESP_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.FetchMailResp.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=1401,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=155,
  serialized_end=169,
)
_sym_db.RegisterEnumDescriptor(_FETCHMAILRESP_DEF)

_RECEIVEATTACHMENTREQ_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.ReceiveAttachmentReq.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=1402,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=212,
  serialized_end=226,
)
_sym_db.RegisterEnumDescriptor(_RECEIVEATTACHMENTREQ_DEF)

_RECEIVEATTACHMENTRESP_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.ReceiveAttachmentResp.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=1403,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=287,
  serialized_end=301,
)
_sym_db.RegisterEnumDescriptor(_RECEIVEATTACHMENTRESP_DEF)

_SENDMAILREQ_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.SendMailReq.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=1405,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=362,
  serialized_end=376,
)
_sym_db.RegisterEnumDescriptor(_SENDMAILREQ_DEF)

_SENDMAILRESP_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.SendMailResp.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=1406,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=394,
  serialized_end=408,
)
_sym_db.RegisterEnumDescriptor(_SENDMAILRESP_DEF)


_FETCHMAILREQ = _descriptor.Descriptor(
  name='FetchMailReq',
  full_name='cardgame.FetchMailReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_mail_id', full_name='cardgame.FetchMailReq.max_mail_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FETCHMAILREQ_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=105,
)


_FETCHMAILRESP = _descriptor.Descriptor(
  name='FetchMailResp',
  full_name='cardgame.FetchMailResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mails', full_name='cardgame.FetchMailResp.mails', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FETCHMAILRESP_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=169,
)


_RECEIVEATTACHMENTREQ = _descriptor.Descriptor(
  name='ReceiveAttachmentReq',
  full_name='cardgame.ReceiveAttachmentReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mail_id', full_name='cardgame.ReceiveAttachmentReq.mail_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RECEIVEATTACHMENTREQ_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=226,
)


_RECEIVEATTACHMENTRESP = _descriptor.Descriptor(
  name='ReceiveAttachmentResp',
  full_name='cardgame.ReceiveAttachmentResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='cardgame.ReceiveAttachmentResp.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RECEIVEATTACHMENTRESP_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=301,
)


_SENDMAILREQ = _descriptor.Descriptor(
  name='SendMailReq',
  full_name='cardgame.SendMailReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='to', full_name='cardgame.SendMailReq.to', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='cardgame.SendMailReq.title', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='cardgame.SendMailReq.content', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SENDMAILREQ_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=376,
)


_SENDMAILRESP = _descriptor.Descriptor(
  name='SendMailResp',
  full_name='cardgame.SendMailResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SENDMAILRESP_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=378,
  serialized_end=408,
)

_FETCHMAILREQ_DEF.containing_type = _FETCHMAILREQ
_FETCHMAILRESP.fields_by_name['mails'].message_type = struct_pb2._MAIL
_FETCHMAILRESP_DEF.containing_type = _FETCHMAILRESP
_RECEIVEATTACHMENTREQ_DEF.containing_type = _RECEIVEATTACHMENTREQ
_RECEIVEATTACHMENTRESP.fields_by_name['result'].message_type = struct_pb2._RESULT
_RECEIVEATTACHMENTRESP_DEF.containing_type = _RECEIVEATTACHMENTRESP
_SENDMAILREQ_DEF.containing_type = _SENDMAILREQ
_SENDMAILRESP_DEF.containing_type = _SENDMAILRESP
DESCRIPTOR.message_types_by_name['FetchMailReq'] = _FETCHMAILREQ
DESCRIPTOR.message_types_by_name['FetchMailResp'] = _FETCHMAILRESP
DESCRIPTOR.message_types_by_name['ReceiveAttachmentReq'] = _RECEIVEATTACHMENTREQ
DESCRIPTOR.message_types_by_name['ReceiveAttachmentResp'] = _RECEIVEATTACHMENTRESP
DESCRIPTOR.message_types_by_name['SendMailReq'] = _SENDMAILREQ
DESCRIPTOR.message_types_by_name['SendMailResp'] = _SENDMAILRESP

FetchMailReq = _reflection.GeneratedProtocolMessageType('FetchMailReq', (_message.Message,), dict(
  DESCRIPTOR = _FETCHMAILREQ,
  __module__ = 'mail_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.FetchMailReq)
  ))
_sym_db.RegisterMessage(FetchMailReq)

FetchMailResp = _reflection.GeneratedProtocolMessageType('FetchMailResp', (_message.Message,), dict(
  DESCRIPTOR = _FETCHMAILRESP,
  __module__ = 'mail_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.FetchMailResp)
  ))
_sym_db.RegisterMessage(FetchMailResp)

ReceiveAttachmentReq = _reflection.GeneratedProtocolMessageType('ReceiveAttachmentReq', (_message.Message,), dict(
  DESCRIPTOR = _RECEIVEATTACHMENTREQ,
  __module__ = 'mail_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.ReceiveAttachmentReq)
  ))
_sym_db.RegisterMessage(ReceiveAttachmentReq)

ReceiveAttachmentResp = _reflection.GeneratedProtocolMessageType('ReceiveAttachmentResp', (_message.Message,), dict(
  DESCRIPTOR = _RECEIVEATTACHMENTRESP,
  __module__ = 'mail_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.ReceiveAttachmentResp)
  ))
_sym_db.RegisterMessage(ReceiveAttachmentResp)

SendMailReq = _reflection.GeneratedProtocolMessageType('SendMailReq', (_message.Message,), dict(
  DESCRIPTOR = _SENDMAILREQ,
  __module__ = 'mail_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.SendMailReq)
  ))
_sym_db.RegisterMessage(SendMailReq)

SendMailResp = _reflection.GeneratedProtocolMessageType('SendMailResp', (_message.Message,), dict(
  DESCRIPTOR = _SENDMAILRESP,
  __module__ = 'mail_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.SendMailResp)
  ))
_sym_db.RegisterMessage(SendMailResp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.zhili.cardgame.protoB\004MailH\003'))
# @@protoc_insertion_point(module_scope)
