# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rank.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# import constant_pb2
# import struct_pb2
from proto import struct_pb2
from proto import constant_pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='rank.proto',
  package='cardgame',
  serialized_pb=_b('\n\nrank.proto\x12\x08\x63\x61rdgame\x1a\x0e\x63onstant.proto\x1a\x0cstruct.proto\"l\n\x0cQueryRankReq\x12%\n\trank_type\x18\x01 \x02(\x0e\x32\x12.cardgame.RankType\x12%\n\trank_time\x18\x02 \x02(\x0e\x32\x12.cardgame.RankTime\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xd0(\"W\n\rQueryRankResp\x12%\n\x07players\x18\x01 \x03(\x0b\x32\x14.cardgame.RankPlayer\x12\x0f\n\x07my_rank\x18\x02 \x01(\x05\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xd1(B\"\n\x18\x63om.zhili.cardgame.protoB\x04RankH\x03')
  ,
  dependencies=[constant_pb2.DESCRIPTOR,struct_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_QUERYRANKREQ_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.QueryRankReq.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=5200,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=148,
  serialized_end=162,
)
_sym_db.RegisterEnumDescriptor(_QUERYRANKREQ_DEF)

_QUERYRANKRESP_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.QueryRankResp.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=5201,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=237,
  serialized_end=251,
)
_sym_db.RegisterEnumDescriptor(_QUERYRANKRESP_DEF)


_QUERYRANKREQ = _descriptor.Descriptor(
  name='QueryRankReq',
  full_name='cardgame.QueryRankReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rank_type', full_name='cardgame.QueryRankReq.rank_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rank_time', full_name='cardgame.QueryRankReq.rank_time', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _QUERYRANKREQ_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=162,
)


_QUERYRANKRESP = _descriptor.Descriptor(
  name='QueryRankResp',
  full_name='cardgame.QueryRankResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='players', full_name='cardgame.QueryRankResp.players', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='my_rank', full_name='cardgame.QueryRankResp.my_rank', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _QUERYRANKRESP_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=251,
)

_QUERYRANKREQ.fields_by_name['rank_type'].enum_type = constant_pb2._RANKTYPE
_QUERYRANKREQ.fields_by_name['rank_time'].enum_type = constant_pb2._RANKTIME
_QUERYRANKREQ_DEF.containing_type = _QUERYRANKREQ
_QUERYRANKRESP.fields_by_name['players'].message_type = struct_pb2._RANKPLAYER
_QUERYRANKRESP_DEF.containing_type = _QUERYRANKRESP
DESCRIPTOR.message_types_by_name['QueryRankReq'] = _QUERYRANKREQ
DESCRIPTOR.message_types_by_name['QueryRankResp'] = _QUERYRANKRESP

QueryRankReq = _reflection.GeneratedProtocolMessageType('QueryRankReq', (_message.Message,), dict(
  DESCRIPTOR = _QUERYRANKREQ,
  __module__ = 'rank_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.QueryRankReq)
  ))
_sym_db.RegisterMessage(QueryRankReq)

QueryRankResp = _reflection.GeneratedProtocolMessageType('QueryRankResp', (_message.Message,), dict(
  DESCRIPTOR = _QUERYRANKRESP,
  __module__ = 'rank_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.QueryRankResp)
  ))
_sym_db.RegisterMessage(QueryRankResp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.zhili.cardgame.protoB\004RankH\003'))
# @@protoc_insertion_point(module_scope)
