# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vip.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# import struct_pb2
# import constant_pb2
from proto import struct_pb2
from proto import constant_pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='vip.proto',
  package='cardgame',
  serialized_pb=_b('\n\tvip.proto\x12\x08\x63\x61rdgame\x1a\x0cstruct.proto\x1a\x0e\x63onstant.proto\"%\n\x13ReceiveVipRewardReq\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\x84 \"H\n\x14ReceiveVipRewardResp\x12 \n\x06reward\x18\x01 \x01(\x0b\x32\x10.cardgame.Reward\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\x85 B!\n\x18\x63om.zhili.cardgame.protoB\x03VipH\x03')
  ,
  dependencies=[struct_pb2.DESCRIPTOR,constant_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_RECEIVEVIPREWARDREQ_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.ReceiveVipRewardReq.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=4100,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=76,
  serialized_end=90,
)
_sym_db.RegisterEnumDescriptor(_RECEIVEVIPREWARDREQ_DEF)

_RECEIVEVIPREWARDRESP_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.ReceiveVipRewardResp.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=4101,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=150,
  serialized_end=164,
)
_sym_db.RegisterEnumDescriptor(_RECEIVEVIPREWARDRESP_DEF)


_RECEIVEVIPREWARDREQ = _descriptor.Descriptor(
  name='ReceiveVipRewardReq',
  full_name='cardgame.ReceiveVipRewardReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RECEIVEVIPREWARDREQ_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=90,
)


_RECEIVEVIPREWARDRESP = _descriptor.Descriptor(
  name='ReceiveVipRewardResp',
  full_name='cardgame.ReceiveVipRewardResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reward', full_name='cardgame.ReceiveVipRewardResp.reward', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RECEIVEVIPREWARDRESP_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=164,
)

_RECEIVEVIPREWARDREQ_DEF.containing_type = _RECEIVEVIPREWARDREQ
_RECEIVEVIPREWARDRESP.fields_by_name['reward'].message_type = struct_pb2._REWARD
_RECEIVEVIPREWARDRESP_DEF.containing_type = _RECEIVEVIPREWARDRESP
DESCRIPTOR.message_types_by_name['ReceiveVipRewardReq'] = _RECEIVEVIPREWARDREQ
DESCRIPTOR.message_types_by_name['ReceiveVipRewardResp'] = _RECEIVEVIPREWARDRESP

ReceiveVipRewardReq = _reflection.GeneratedProtocolMessageType('ReceiveVipRewardReq', (_message.Message,), dict(
  DESCRIPTOR = _RECEIVEVIPREWARDREQ,
  __module__ = 'vip_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.ReceiveVipRewardReq)
  ))
_sym_db.RegisterMessage(ReceiveVipRewardReq)

ReceiveVipRewardResp = _reflection.GeneratedProtocolMessageType('ReceiveVipRewardResp', (_message.Message,), dict(
  DESCRIPTOR = _RECEIVEVIPREWARDRESP,
  __module__ = 'vip_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.ReceiveVipRewardResp)
  ))
_sym_db.RegisterMessage(ReceiveVipRewardResp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.zhili.cardgame.protoB\003VipH\003'))
# @@protoc_insertion_point(module_scope)
